# Generated by Django 3.1.7 on 2021-03-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='data_admissao',
        ),
    ]
