# Generated by Django 3.1.7 on 2021-03-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210302_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='primeiro_registro',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='quarto_registro',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='segundo_registro',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='terceiro_registro',
            field=models.TimeField(default=0),
        ),
    ]
